"""Turns raw llama-bench rows into a merged comparison table, a winner
recommendation, and human-readable report artifacts (JSON/CSV/Markdown)."""

from __future__ import annotations

import csv
import json
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path


@dataclass
class ConfigResult:
    quant: str
    threads: int
    batch: int
    model_size_mib: float
    n_params: int
    ttft_ms: float
    pp_tokens_per_s: float
    tg_tokens_per_s: float
    mock: bool = False


def merge_rows(rows: list[dict]) -> list[ConfigResult]:
    """Pair up each sweep point's pp-only and tg-only llama-bench rows."""
    by_key: dict[tuple, dict] = {}

    for row in rows:
        key = (row["armtune_quant"], row["n_threads"], row["n_batch"])
        entry = by_key.setdefault(key, {})
        if row.get("n_gen", 0) == 0 and row.get("n_prompt", 0) > 0:
            entry["pp"] = row
        elif row.get("n_prompt", 0) == 0 and row.get("n_gen", 0) > 0:
            entry["tg"] = row

    results = []
    for (quant, threads, batch), entry in by_key.items():
        pp = entry.get("pp")
        tg = entry.get("tg")
        if pp is None or tg is None:
            continue  # incomplete pair, skip
        results.append(
            ConfigResult(
                quant=quant,
                threads=threads,
                batch=batch,
                model_size_mib=round(pp["model_size"] / (1024 * 1024), 1),
                n_params=pp["model_n_params"],
                ttft_ms=round(pp["avg_ns"] / 1e6, 2),
                pp_tokens_per_s=round(pp["avg_ts"], 2),
                tg_tokens_per_s=round(tg["avg_ts"], 2),
                mock=bool(pp.get("armtune_mock", False)),
            )
        )
    results.sort(key=lambda r: r.tg_tokens_per_s, reverse=True)
    return results


def pick_winners(results: list[ConfigResult]) -> dict[str, ConfigResult]:
    if not results:
        raise ValueError("No complete (pp + tg) result pairs to rank.")

    fastest = max(results, key=lambda r: r.tg_tokens_per_s)
    lowest_latency = min(results, key=lambda r: r.ttft_ms)

    # "Best value": within 10% of the fastest tg throughput, smallest on disk.
    threshold = fastest.tg_tokens_per_s * 0.90
    candidates = [r for r in results if r.tg_tokens_per_s >= threshold]
    best_value = min(candidates, key=lambda r: r.model_size_mib)

    best_per_quant: dict[str, ConfigResult] = {}
    for r in results:
        cur = best_per_quant.get(r.quant)
        if cur is None or r.tg_tokens_per_s > cur.tg_tokens_per_s:
            best_per_quant[r.quant] = r

    return {
        "fastest_throughput": fastest,
        "lowest_ttft": lowest_latency,
        "best_value": best_value,
        **{f"best_{q}": v for q, v in best_per_quant.items()},
    }


def write_artifacts(
    raw_rows: list[dict],
    results: list[ConfigResult],
    winners: dict[str, ConfigResult],
    out_dir: Path,
    model_label: str,
    cpu_label: str,
) -> dict[str, Path]:
    out_dir.mkdir(parents=True, exist_ok=True)
    paths: dict[str, Path] = {}

    raw_path = out_dir / "results_raw.json"
    raw_path.write_text(json.dumps(raw_rows, indent=2))
    paths["raw_json"] = raw_path

    csv_path = out_dir / "results.csv"
    with csv_path.open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=list(asdict(results[0]).keys()))
        writer.writeheader()
        for r in results:
            writer.writerow(asdict(r))
    paths["csv"] = csv_path

    md_path = out_dir / "report.md"
    md_path.write_text(_render_markdown(results, winners, model_label, cpu_label))
    paths["markdown"] = md_path

    winner = winners["fastest_throughput"]
    cmd_path = out_dir / "recommended_launch.sh"
    cmd_path.write_text(
        "#!/usr/bin/env bash\n"
        "# Generated by armtune - fastest measured config for this host.\n"
        f"# quant={winner.quant} threads={winner.threads} batch={winner.batch}\n"
        f"./llama-server -m models/<your-model>-{winner.quant}.gguf "
        f"-t {winner.threads} -b {winner.batch} --host 0.0.0.0 --port 8080\n"
    )
    cmd_path.chmod(0o755)
    paths["launch_script"] = cmd_path

    return paths


def _render_markdown(
    results: list[ConfigResult],
    winners: dict[str, ConfigResult],
    model_label: str,
    cpu_label: str,
) -> str:
    is_mock = any(r.mock for r in results)
    lines = []
    lines.append(f"# ArmTune sweep report\n")
    lines.append(f"- Model: `{model_label}`")
    lines.append(f"- Host CPU: `{cpu_label}`")
    lines.append(f"- Generated: {datetime.now(timezone.utc).isoformat(timespec='seconds')}")
    if is_mock:
        lines.append(
            "\n> **SYNTHETIC DEMO DATA.** This report was generated with "
            "`--mock` for pipeline testing and does not reflect real hardware "
            "performance. Re-run without `--mock` on an Arm64 target for "
            "real numbers.\n"
        )
    lines.append("")

    w = winners["fastest_throughput"]
    v = winners["best_value"]
    l = winners["lowest_ttft"]
    lines.append("## Recommended configs\n")
    lines.append(
        f"- **Fastest throughput:** `{w.quant}`, {w.threads} threads, batch {w.batch} "
        f"→ **{w.tg_tokens_per_s} tok/s** generation, {w.ttft_ms} ms TTFT, {w.model_size_mib} MiB"
    )
    lines.append(
        f"- **Best value (smallest within 10% of fastest):** `{v.quant}`, {v.threads} threads, "
        f"batch {v.batch} → {v.tg_tokens_per_s} tok/s, **{v.model_size_mib} MiB**"
    )
    lines.append(
        f"- **Lowest time-to-first-token:** `{l.quant}`, {l.threads} threads, batch {l.batch} "
        f"→ **{l.ttft_ms} ms TTFT**"
    )
    lines.append("")

    lines.append("## Full sweep (sorted by generation throughput)\n")
    lines.append("| quant | threads | batch | size (MiB) | TTFT (ms) | prompt t/s | gen t/s |")
    lines.append("|---|---:|---:|---:|---:|---:|---:|")
    for r in results:
        lines.append(
            f"| {r.quant} | {r.threads} | {r.batch} | {r.model_size_mib} | "
            f"{r.ttft_ms} | {r.pp_tokens_per_s} | {r.tg_tokens_per_s} |"
        )
    lines.append("")

    lines.append("## Best config per quantization level\n")
    lines.append("| quant | threads | batch | size (MiB) | TTFT (ms) | gen t/s |")
    lines.append("|---|---:|---:|---:|---:|---:|")
    for key, r in winners.items():
        if not key.startswith("best_") or key == "best_value":
            continue
        quant_name = key[len("best_"):]
        lines.append(f"| {quant_name} | {r.threads} | {r.batch} | {r.model_size_mib} | {r.ttft_ms} | {r.tg_tokens_per_s} |")
    lines.append("")

    return "\n".join(lines)
